### ISSUE TITLE
Unable to load HTAN image for specific case

### ISSUE THREAD

**Issue by fedorov** [ImagingDataCommons/idc-slim#84]
@dclunie @cgorman any thoughts?

https://viewer.imaging.datacommons.cancer.gov/slim/studies/2.25.174442227011591161839224535127252003551/series/1.3.6.1.4.1.5962.99.1.2352175091.700331458.1655914616819.4.0

<img width="1228" alt="image" src="https://github.com/ImagingDataCommons/idc-slim/assets/313942/5e25e148-88f5-48b2-ba33-524d3f8bb14d">

**Comment by fedorov** [comment]
Curiously, that is the only study from the HTAN-HMS collection that does not have the PR series!

**Comment by rodrigobasilio2022** [comment]
The dicom-microscopy-viewer package that slim uses expects that an image pyramid metadata should have in the attributes extent and resolutions a matrix 2d, but in the image in question they are 1d array attributes. Is that correct or i can assume they should be 1D arrays as in the file? 
Also there is a divergence in the pixelsSpacing in one of the pyramids of more than 1e-6, the accepted difference in the package. The divergence is less than 1e-5, so we could update the package, if the case.

**Comment by rodrigobasilio2022** [comment]
Studying more the code it seems that issue is a bug in the code of the dicom-microscopy-viewer package: the two calculated attributes are in fact 1d arrays. @fedorov , can you make me an collaborator in 
https://github.com/ImagingDataCommons/dicom-microscopy-viewer 
so i can create a PR to solve the problem?

**Comment by rodrigobasilio2022** [comment]
PR opened and tested.

**Comment by fedorov** [comment]
Confirmed this is now fixed in IDC test tier!
